name: Style Dictionary Workflow
on: [push]

jobs:
build:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v3
- name: Set Node.js
uses: actions/setup-node@v3
with:
node-version: latest
registry-url: 'https://npm.pkg-github.com'
- run: npm init -y && npm install style-dictionary@prerelease @tokens-studio/sd-transforms
- run: node build-tokens.mjs
- uses: stefanzweifel/git-auto-commit-action@v4
with:
commit_message: Update Tokens
